### ISSUE TITLE
Installation Doesn't Complete on Ubuntu 18.04

### ISSUE THREAD

**Issue by IanKnighton** [microsoft/OMS-Agent-for-Linux#996] opened 2019-07-16 15:29 UTC
Maybe I'm missing something, but I can't seem to make this work on any of my servers. I would like to move all of my monitoring to our Azure instance and this is where I'm hung up. The other servers are hosted in Linode if that matters at all.

I'm using the command:
`sudo wget https://raw.githubusercontent.com/Microsoft/OMS-Agent-for-Linux/master/installer/scripts/onboard_agent.sh && sh onboard_agent.sh -w xxxx -s xxxxx -d opinsights.azure.com`

And this is the end of the output.

```console
Successfully applied metaconfig.

VERBOSE from OMS_MetaConfigHelper.py: Successfully configured omsconfig.
----- Updating bundled packages -----
Checking if Apache is installed ...
  Apache not found, will not install
Checking if Docker is installed...
  Docker not found. Docker agent will not be installed.
Checking if MySQL is installed ...
  MySQL not found, will not install
Checking if required dependencies for auoms are installed...
Extracting...
Updating auoms ...
----- Updating package: auoms (auoms-1.3.0-3.universal.x64) -----
Selecting previously unselected package auoms.
(Reading database ... 164294 files and directories currently installed.)
Preparing to unpack auoms-1.3.0-3.universal.x64.deb ...
Unpacking auoms (1.3.0.3) ...
Setting up auoms (1.3.0.3) ...
Shell bundle exiting with code 0
```

I don't receive any indication of an error nor do I ever have the servers show up in my Azure instance. I'm not sure what I'm doing wrong here.

**Comment by othmanaljundi-microsoft** [comment] 2019-07-22 15:28
would you please ensure that you have :
# ls -ld /etc/opt/microsoft/omsagent

**Comment by IanKnighton** [comment] 2019-07-22 16:43
Output:
```
drwxr-xr-x 4 root root 4096 Jul 16 15:25 /etc/opt/microsoft/omsagent
```

**Comment by jackycsl** [comment] 2019-08-07 04:11
Is there any workaround for this issue?
I am facing the same problem as well on Ubuntu 18.04

`Checking host architecture ...
Extracting...
----- Upgrading package: omi (omi-1.6.2-0.ulinux.x64) -----
Skipping package since existing version >= version available
Trying to stop omi with systemctl
omi is stopped.
Trying to start omi with systemctl
omi is started.
----- Upgrading package: omsagent (omsagent-1.11.0-9.universal.x64) -----
Skipping package since existing version >= version available
----- Upgrading package: omsconfig (omsconfig-1.1.1-926.x64) -----
Skipping package since existing version >= version available
Trying to stop omi with systemctl
omi is stopped.
Trying to start omi with systemctl
omi is started.
----- Updating bundled packages -----
Checking if Apache is installed ...
  Apache not found, will not install
Checking if Docker is installed...
  Docker version greater or equal than 17.* found. Docker agent will be installed
Extracting...
Updating container agent ...
----- Updating package: docker-cimprov (docker-cimprov-1.0.0-37.universal.x86_64) -----
Skipping package since existing version >= version available
Checking if MySQL is installed ...
  MySQL not found, will not install
Extracting...
Updating auoms ...
----- Updating package: auoms (auoms-2.0.0-13.universal.x64) -----
Skipping package since existing version >= version available
Shell bundle exiting with code 0`

**Comment by FLavalliere** [comment] 2020-03-19 16:35
Any informations on this issue, did you managed to find the root cause etc?

**Comment by TheMMcOfficial** [comment] 2020-06-18 12:41
I have similar issue with the 18.04. The directories in /etc/opt/microsoft ... are not create in the script and I need to do an "oms-angent.sh --install --force" to install the oms-agent. The script configure some things with the workspace that I have not with this methode... I have back on a Ubuntu 16.04 and the command work has intended.

**Closed** 2024-09-11 14:04 UTC
