### ISSUE TITLE
Path to ruby binary

### ISSUE THREAD

**Issue by michaelschulz** [Microsoft/OMS-Agent-for-Linux#4] opened 2015-11-10 23:14 UTC
In OMS-Agent-for-Linux/source/code/plugins/in_omi.rb and OMS-Agent-for-Linux/source/code/plugins/in_oms_omi.rb the ruby path points to /usr/local/bin/ruby. The default on most systems would be /usr/bin/ruby.

**Comment by terbolous** [comment] 2015-11-11 09:22
Why not use '/usr/bin/env ruby'?

**Comment by jeffaco** [comment] 2015-11-11 16:02
Part of the issue is that we require Ruby 2.2.0 for a variety of reasons, and I'm not aware of any systems today that ship a version of Ruby v2.2.0 by default.

We'll have full instructions posted here shortly for how to build from source, and that will include a few different mechanisms for how to set up the version of Ruby that we need.

**Comment by michaelschulz** [comment] 2015-11-11 16:13
By convention, the binary that ships with the system would be in /usr/bin, /usr/local/bin would be used for non system distribution binaries. So if we need a different version, then it would make sense to leave it as is. Using /usr/bin/env would use the first ruby that would be found in $PATH but the user may have multiple versions installed. 
Are we locked on 2.2.0 or 2.2.x? Latest release is 2.2.3.

**Comment by jeffaco** [comment] 2015-11-11 17:10
We are locked into 2.2.0, as that's what we test with. Other versions may work, but won't be supported.

In the end, when we include build instructions, there may be some slight changes to some of the code to facilitate open-source building. For now, I'd suggest holding off until we update for open source, which should hopefully be in a week or less. The basics are all here, but things like path may change, and we'll make minor changes to the sources here to facilitate that.

**Closed** 2016-01-09 01:18 UTC
