### ISSUE TITLE
Constant 95% CPU Utilization

### ISSUE THREAD

**Issue by sedouard** [Microsoft/OMS-Agent-for-Linux#398] opened 2017-03-06 03:26 UTC
Hey there. One of our Ubuntu 14.04 machines are constantly running at at 95% CPU utilized by `omiagent`.

This is recent maybe in the last week. Any recent updates to ARM IaaS VMs in central US that may have caused this?

**Comment by jonjander** [comment] 2017-03-06 10:02
I have the same problem on a Red Hat 7 in west europe

looks like something is starting hundreds of omsagent processes.

**Comment by lagalbra** [comment] 2017-03-07 19:21
Can you please provide the printouts of process name, PID, and CPU usage you're seeing, either from the machine itself or your OMS workspace?

Is the high CPU coming from `omiagent` or `omsagent`? If it is the `omiagent`, I would recommend creating an issue in the [OMI repo](https://github.com/Microsoft/omi).

**Comment by lagalbra** [comment] 2017-03-07 19:23
Please also provide the version number of the OMSAgent installed on the machine.

**Comment by lagalbra** [comment] 2017-04-03 23:19
@sedouard @jonjander Please update this thread with the requested information; otherwise, this issue will be closed.

**Comment by toutougabi** [comment] 2017-04-12 17:51
we have the same issue, we had to remove the agent, it was causing cpu stalls throughout all of our nodes.

i have a case opened with part of the team in seattle, if you want i can share the details or the support #, we collected some data but ultimately, we had to remove the agent because we had too many issue.

**Comment by fperez-solidq** [comment] 2017-04-21 19:36
I have the same problem. The connection between OMS and the Linux virtual machine works perfectly, the problem comes when I reboot the machine. When the OMS machine is restarted, it starts using the entire CPU of the machine. I have attached a graph of what happened.

![oms-problem](https://cloud.githubusercontent.com/assets/24895358/25293249/43e5826a-26da-11e7-8c94-31387f0939aa.png)

**Comment by lagalbra** [comment] 2017-04-21 20:30
Again, please specify: Is the high CPU coming from omiagent or omsagent? If it is the omiagent, I would recommend creating an issue in the OMI repo.

1. Find the PID of the omsagent: `cat /var/opt/microsoft/omsagent/run/omsagent.pid`
2. Print out the CPU usage of that process: `ps -p <PID> -o %cpu`
3. Find the PID of the omiagent: `cat /var/opt/omi/run/omiserver.pid`
4. Print out the CPU usage of that process

**Comment by fperez-solidq** [comment] 2017-04-27 07:21
Hello again, yes the problem is with the omiagent process. I can't get the CPU usage of the omiagent because I had to killed it.

I will report this issue to OMI repo.
Thank you for your reply

**Comment by lagalbra** [comment] 2017-04-27 16:44
Closing this issue; the problem will be reported to the [OMI team](https://github.com/Microsoft/omi/issues).

**Closed by lagalbra** 2017-04-27 16:44 UTC

**Comment by bora89** [comment] 2018-04-04 16:46
I have the same issue: Ubuntu + Docker
![](http://joxi.ru/nAyGyVFX1GDLmZ?d=1)
