### ISSUE TITLE
Ubuntu 20.04 LTS support

### ISSUE THREAD

**Issue by mvalee** [microsoft/OMS-Agent-for-Linux#1216] opened 2020-06-27 08:43 UTC
Support for Ubuntu 20.04 LTS is missing.

Attempts to link a VM to Log Analytics workspace in Azure portal are resulting in 'Unknown error: deployment failed'.

Current status of the extension in Azure portal:
![image](https://user-images.githubusercontent.com/12297559/85918250-4a883380-b861-11ea-9dd9-354589a35f8b.png)

Command:
```bash
tail /var/log/azure/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux/extension.log
```
Output:
```
2020/06/26 23:17:06 omsagent-1.13.7-0.universal.x64.sh: OK
2020/06/26 23:17:06 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.13.13] ShellBundle signing verification succeeded
2020/06/26 23:17:06 ERROR:Unsupported operating system: Ubuntu 20.04
2020/06/26 23:17:06 ERROR:[Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.13.13] Unsupported operating system: Ubuntu 20.04
2020/06/26 23:17:06 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.13.13] Install,failed,51,Unsupported operating system: Ubuntu 20.04
```

**Comment by taapawi2** [comment] 2020-07-20 06:53
This is partly due to python version default in Ubuntu 20.04
Agent can be installed manually

**Comment by mvalee** [comment] 2020-07-21 05:59
I'm not sure if there was any change to this since posting the issue, but I remember that at the time of posting the issue both methods were tried:

1. Install via Azure portal GUI (Extension as well as via Log Analytics connect a VM)
2. Direct manual install via SSH terminal - as described in the docs at https://docs.microsoft.com/en-gb/azure/azure-monitor/platform/agent-linux#install-the-agent-manually

Method 1 resulted in no error message except the "Unkown error" in the Azure portal, method 2 resulted in VM logs posted above: "Unsupported operating system: Ubuntu 20.04".

I have not tried a manual downgrade of the python version on the VM however.

**Comment by ranieuwe** [comment] 2020-08-26 05:16
This is due to a change in Ubuntu 20.04 and the command `python` not being available. This can be resolved by installing `python-is-python3` as such:

```
sudo apt-get install python-is-python3
```

And then installing the omsagent again. There are some other python3 issues, but otherwise the install works. 

Unfortunately this means that provisioning the omsagent through the portal or cli will fail unless the install of python-is-python3 is executed prior.

**Comment by ranieuwe** [comment] 2020-08-26 05:41
Additionally, it then fails on any subsequent running because pip is not installed :( Had to install pip for python2 and python2 manually.. after that it works for that too. Would be great to see this compat check fixed.

**Comment by ranieuwe** [comment] 2020-08-26 06:03
@hestolz any update on when new Linux dists are getting an update for omsagent? Currently they can not be monitored on Azure.

**Comment by elabbarw** [comment] 2020-08-31 07:45
> @hestolz any update on when new Linux dists are getting an update for omsagent? Currently they can not be monitored on Azure.

The answer I got from MS after raising the issue with the PG is "the end of September"

**Comment by hestolz** [comment] 2020-10-06 05:41
Hi @mvalee, @ranieuwe, extension 1.13.27-0 is now released to all public regions (as well as on [GitHub](https://github.com/microsoft/OMS-Agent-for-Linux/releases/tag/OMSAgent_v1.13.27-0)), we have eliminated the python2 and python aliasing requirements and added official support for Ubuntu 20.04. Please give the new version a try.

**Closed by hestolz** 2020-10-06 05:41 UTC

**Comment by tomkingchen** [comment] 2020-10-17 22:21
@hestolz can confirm the oms agent onboard script does install the agent for Ubuntu20.04. However, the uupdate management feature of the agent will not work by default due to Hybrid worker not starting. The issue is fixed after install Python 2.7 and reboot.

**Comment by ghandim** [comment] 2020-11-06 06:33
IMO works already not yet out of the box as expected. Switched this week to 20.04-LTS and the nodes are listed with state "not configured" in our Automation Accounts. Any hints?

**Comment by eskes1** [comment] 2020-12-07 10:11
Any update on this?  I now it is Closed. But I think it should not be closed if it is not fully fixed.

**Comment by taapawi2** [comment] 2021-01-14 08:16
The latest version of the agent now support Python2 and Python3 side by side with an official support of Ubuntu 20.04.

I would say that this is closed now

**Comment by ghandim** [comment] 2021-01-29 13:15
@taapawi2 Can confirm. Now it is working for my new 20.04 machines created this week.
