### ISSUE TITLE
Damaged or missing omsadmin.conf causes VM to not boot-up

### ISSUE THREAD

**Issue by mabicca** [Microsoft/OMS-Agent-for-Linux#614] opened 2017-12-12 02:40 UTC
Issue has been seen a few times and can be easily reproduced.

1) Deploy any Linux VM, in this case I tested with Red Hat 6.9
2) Install and onboard the OMS Agent on any Linux VM using the link from log analytics
3) Move the omsadmin.conf file to let's say omsadmin.conf.old , usually located under:
/etc/opt/microsoft/omsagent/{YOUR_WORKSPACE_ID/conf/omsadmin.conf
4) Reboot the VM

The VM will not finish booting up properly, so no SSH connectivity is possible, you should see a similar message like:

/opt/microsoft/omsagent/bin/service_control: line 159: /etc/opt/microsoft/omsagent/46023ff6-4340-4615-9ace-1d24f5a035ca/conf/omsadmin.conf: No such file or directory

Starting Operations Management Suite agent (46023ff6-4340-4615-9ace-1d24f5a035ca): hv_balloon: Received INFO_TYPE_MAX_PAGE_CNT
hv_balloon: Data Size is 8

-
Even if the config file is damaged, we should be able to fail starting the service or something, but not leave the VM on a unavailable state.

**Comment by marinnedea** [comment] 2017-12-13 07:30
Same issue appears if you get multiple symbolic links pointing to different workspace IDs in the /etc/rc3.d directory ( check for S50omsagent symbolic links). Seems the problem is caused by an update of the OMS Agent that didn't cleared the old symbolic links.
The VM becomes un-bootable because of this bug.. please threat this with high priority!

`
Starting Operations Management Suite agent (480c37eb-06c3-4202-8d54-4e6179bb4c9f): WARN The ChangeTracking inventory xml file does not exists{}[  OK  ]
/opt/microsoft/omsagent/bin/service_control: line 159: /etc/opt/microsoft/omsagent/ae44dc42-1f53-4d81-a3b0-f64f1a9535dd/conf/omsadmin.conf: No such file or directoryStarting Operations Management Suite agent (ae44dc42-1f53-4d81-a3b0-f64f1a9535dd): Redirecting File System Framework Version 0.10 <www.redirfs.org> with TrendMicro Patch 10.1.0.382
register_chrdev(gsch_dev) done: 247
register_chrdev(ac_dev) done: 246
gsch: loading vfs-filter 10.1.0.382: OK
gsch_dev_open(gsch_dev) doing
gsch_dev_open() done: pid:1500(ds_am)
cannot uninstall hooks if location of sys_call_table is unknown
gsch_remove_hooks(&gsch_hooks) done: -22
gsch_install_hooks(&gsch_hooks) done: 0
gsch_redirfs_add_mnt(/tmp @ tmpfs[1021994(tmpss)]) done: 0
gsch_redirfs_add_mnt(/var/crash @ /dev/mapper/vg_system_logs-lv_varcrash[ef53(ext4)]) done: 0
gsch_redirfs_add_mnt(/var @ /dev/mapper/vg_system_logs-lv_var[ef53(ext4)]) done: 0
gsch_redirfs_add_mnt(/boot @ /dev/sda1[ef53(ext4)]) done: 0
gsch_redirfs_add_mnt(/proc/bus/usb @ /proc/bus/usb[9fa2(usbfs)]) done: 0
gsch_redirfs_add_mnt(/ @ /dev/mapper/vg_system-lv_root[ef53(ext4)]) done: 0
gsch_redirfs_add_mnt(/dev/shm @ tmpfs[1021994(tmpfs)]) done: 0
gsch_redirfs_add_mnt(/dev @ devtmpfs[1021994(devtmpfs)]) done: 0
gsch_redirfs: loaded
hv_balloon: Received INFO_TYPE_MAX_PAGE_CNT
hv_balloon: Data Size is 8
`
In the log you can see the OMS tries to start from an workspace ID that doesn't exists.
The interesting part is that it triggers a "memory ballooning" error in the end, which may be the final reason the VM no longer boots.

**Comment by silverl** [comment] 2017-12-13 16:12
I've also seen the issue that @marinnedea pointed out -- multiple symbolic links left behind, such that systemd tries to start multiple versions of omsagent at once. I've taken to checking for omsagent updates and manually clearing out the old installations.

**Comment by mabicca** [comment] 2018-01-04 00:32
Any updates on this report?

**Comment by NarineM** [comment] 2018-01-23 22:22
multiple workspaces are not supported . please run omsagent*.sh bundle with --purge to remove old workspace information, then run the bundle with --upgrade.

**Comment by NarineM** [comment] 2018-01-23 22:26
for the other issue reported in this thread with machine reboot please try latest version of agent and let me know if it is still happening.

**Comment by NarineM** [comment] 2018-01-23 22:33
If the customer wants to uninstall the agent, they have to do it properly using the installer with –purge option to remove omsagent package from their linux system. It is unusual for someone just delete some files from the machine manually if their VM is still running applications that use or depend on these files. Please ask them to uninstall omsagent. If this file is removed from the system, agent is no use .

**Comment by NarineM** [comment] 2018-01-23 22:33
Closing as external "customer error"

**Closed by NarineM** 2018-01-23 22:33 UTC

**Comment by silverl** [comment] 2018-01-23 23:11
Nobody is intentionally trying to run multiple workspaces. When the agent auto-updates, it is not cleaning up after itself properly, and it's leaving multiple workspaces behind. "customer error" ... really?

**Comment by NarineM** [comment] 2018-01-23 23:16
My response with "customer error " was related to original issue that Bruno reported. Other issues discussed in this thread are unrelated to the file removal issue he had. Please do not confuse these together. Please file a separate issue about symbolic link. I am suprised to hear that someone was able to install multiple instance of omsagent and get into symbolic link issues since it is not a supported scenario nor ever worked.

**Comment by NarineM** [comment] 2018-01-23 23:20
onboarding agent into multiple workspaces also is not a scenario we support in azure.

**Comment by marinnedea** [comment] 2018-01-25 08:14
So.. I see no Bruno reporting anything in this thread. Both the issues reported by Marco and me are exactly the same, just seen from different perspective. The problem appears during AUTO-update and in both cases in breaks the workspace links by not cleaning the old symlinks before creating new ones... So @NarineM  .. I have no idea why you closed this, but it looks to me you're on the wrong track mate...

**Comment by NarineM** [comment] 2018-01-25 11:24
@marinnedea 
the issue with symbolic link is not related to the issue with service restart failing when omsadmin.conf is manually deleted from the machine. 
Again please file a different issue for symbolic links.

**Comment by mabicca** [comment] 2018-08-21 22:32
Is there a separate issue opened for this? I am still seeing customers having this issue. The same exact reported issue at the top.

**Comment by shpimpal** [comment] 2018-08-29 11:53
Can you get full boot up logs ? And what versions of kernel are being run.

This may not be related to OMS agent, I tried with Ubuntu 16.04 - moved omsadmin.conf to omsadmin.conf.old and restarted the VM. It booted up fine.

You could also check by moving this file somewhere else and running "/opt/microsoft/omsagent/bin/service_control restart", it fails with error 1 and does not block.

**Comment by NaumiNet** [comment] 2018-08-29 13:17
@shpimpal 

Red Hat 6.x like the original post of this thread.

OMS has been completely removed from 190 nodes. It became business critical because the nodes didn't boot up.

Suggestion: 
Make sure the OS boots up completely before third party services are started to make sure you can connect to it via ssh (in case OMS fails at boot up).

**Comment by shpimpal** [comment] 2018-09-11 06:35
Hi, I could repro on rhel 6.x. Fixed with commit #779. Although this is not a usual case that omsadmin.conf goes missing without external intervention.
As for the multiple symlinks issue, it is not a supported scenario and should not happen now with latest releases. If you observe it, please open another issue for that. Thanks!

**Comment by juhlee-microsoft** [comment] 2022-09-07 18:24
@shpimpal It's hard to believe this patch is the fix. Here people (including me) are looking for the solution why this file is missing and how we fix this issue, but this PR is for just conditional print only.

**Comment by shpimpal** [comment] 2022-09-08 05:03
@juhlee-microsoft, please look at the title of the issue or PR. It says VM boot issue fix and not the missing conf file fix. Also, this fix has not just prints but also an exit statement which I suppose is to fail gracefully (and perhaps give up OMS initialization) rather than blocking the VM boot with unwanted outcomes. 
Btw it's been years I haven't worked on this project, so I don't remember much. If you face any issues, please reach out to current owners of the project.
